# Question 1 - Singular Value Decomposition and Principal Component Analysis

In [2]:
import numpy as np
from scipy import linalg

Initialize the matrix.

In [4]:
M = np.array([[1, 2], [2, 1], [3, 4], [4, 3]])
M

array([[1, 2],
       [2, 1],
       [3, 4],
       [4, 3]])

Compute the SVD of $M$.

In [59]:
U, S, VT = linalg.svd(M, full_matrices=False)
print("U =\n", U, "\nS =\n", S, "\nVT =\n", VT)

U =
 [[-0.27854301  0.5       ]
 [-0.27854301 -0.5       ]
 [-0.64993368  0.5       ]
 [-0.64993368 -0.5       ]] 
S =
 [7.61577311 1.41421356] 
VT =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


Compute the eigenvalue decomposition of $M^T M$.

In [47]:
A = np.matmul(M.T, M)
Evals, Evecs = linalg.eigh(A)
print("Evals =\n", Evals, "\nEvecs =\n", Evecs)

Evals =
 [ 2. 58.] 
Evecs =
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


Sort eigenvalues in descending order.

In [55]:
Evals = sorted(Evals, reverse=True)
Evecs[[0, 1]] = Evecs.T[[1, 0]].T
print("Evals =\n", Evals, "\nEvecs =\n", Evecs)

Evals =
 [58.0, 2.0] 
Evecs =
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


We can see that $-V^T$ is same as $Evecs$ reflected by $x$-axis.

In [58]:
np.matmul(Evecs, np.array([[- 1, 0], [0, 1]]))

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

Check to see if results from $(c) M^T M = Evecs \cdot diag(Evals) \cdot Evecs^T$ and $(d) M^T M = V \cdot diag(S)^2 \cdot V^T$ are true.

In [56]:
np.matmul(np.matmul(Evecs, np.diag(Evals)), Evecs.T)

array([[30., 28.],
       [28., 30.]])

In [51]:
V = - VT.T
np.matmul(np.matmul(V, np.matmul(np.diag(S), np.diag(S))), V.T)

array([[30., 28.],
       [28., 30.]])

In [60]:
np.matmul(VT, Evecs)

array([[-1.00000000e+00,  8.86511593e-17],
       [ 1.00875766e-16,  1.00000000e+00]])